sudo: false

language: c

git:
  submodules: false

before_script:
  -git submodules --intit --recursive

script:
  - cd ./simple_shell
  - COMPILE=$(cat ../modules_list | tr '\r\n' ' ')
  - gcc -Wall -Werror -Wextra -pedantic -g3 -std=c90 $COMPILE -o masu
  - ls -l
  - ls -l | ./masu
  - echo "Hello" | ./masu
  - echo "Done!"
