sudo: false

language: c

git:
  submodules: true

env:
  - SHELL_NAME="marsu" COMPITE="nile"
  
before_script:
  - pwd
  - git pull
  - export COMPILE=$(cat modules_list | tr '\r\n' ' ')
  - echo $COMPILE
  - cd ./test_suite
  - sed  "s/ENTER_NAME_OF_YOUR_SHELL_HERE/${SHELL_NAME}/g" config

script:
  - cd ./simple_shell
  - gcc -Wall -Werror -Wextra -pedantic -g3 -std=c90 $COMPILE -o $SHELL_NAME
  - echo "ls -l" | ./$SHELL_NAME
  - echo "Hello" | ./$SHELL_NAME
  - echo "Done!"
