sudo: required

language: c

git:
  submodules: true

before_script:
  - cd ./simple_shell
  - COMPILE=$(cat ../modules_list | tr '\r\n' ' ')
  - gcc -Wall -Werror -Wextra -pedantic -g3 -std=c90 $COMPILE -o masu
  - cp .. && cd ..

script:
  - echo "Hello"
  - ./masu
  - echo "Hello"
  - exit
  - echo "Done!"
