

sudo: required

language: c

services:
  - docker

before_install:
  - docker pull lemures/dockworker
  - docker run -it --user 1337:1337 --workdir /home/goliath lemures/dockworker

git:
  submodules: true

env:
  - SHELL_NAME="marsu" COMPITE="nile" REPO="nil"
  
before_script:
  - git pull --recurse-submodules
  - git submodule update --remote --recursive
  - export REPO=$(pwd)
#   - export COMPILE=$(cat modules_list | tr '\r\n' ' ')
#   - echo $COMPILE
  - cd ./test_suite
  - sed  -i "s/ENTER_NAME_OF_YOUR_SHELL_HERE/${SHELL_NAME}/g" config
  - cd $REPO

script:
  - cd ./simple_shell
#   - gcc -Wall -Werror -Wextra -pedantic -g3 -std=c90 $COMPILE -o $SHELL_NAME
  - gcc -Wall -Werror -Wextra -pedantic -g3 -std=c90 *.c -o $SHELL_NAME
  - echo ls | bash
  - mv $SHELL_NAME ../test_suite && cd ../test_suite
  - ./check_simple_shell.bash
  
